### ISSUE TITLE
Improved wiki

### ISSUE THREAD

**Issue by gunicsba** [farmerbriantee/AgOpenGPS_Boards#1]
Hello,

I did some changes on the wiki, maybe worth adding.
https://github.com/gunicsba/AgOpenGPS_Boards/wiki/_compare/c7f826a9be92b5391a511e88c997eaecd4dd08b3...51997befe7c1a4773c5db88714f4913b6c6381d3

**Comment by gunicsba** [comment]
FYI: @lansalot  @farmerbriantee

**Comment by lansalot** [comment]
Merged, thanks!
